# Generated by Django 6.0.4 on 2026-04-12 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_paid', 'status', 'created_at'], name='orders_orde_is_paid_719609_idx'),
        ),
    ]
