# Generated by Django 6.0.4 on 2026-04-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orders_orde_is_paid_719609_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, help_text='e.g., BlueDart, Delhivery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='Snapshot of product name at time of purchase', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Snapshot of SKU', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending (Payment Awaited)'), ('Failed', 'Failed (Payment Rejected)'), ('Paid', 'Paid (Order Confirmed)'), ('On Hold', 'On Hold (Reviewing)'), ('Processing', 'Processing (Packing)'), ('Shipped', 'Shipped (Dispatched)'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled (By User/Admin)'), ('Returned', 'Returned (Item Received Back)'), ('Refunded', 'Refunded (Money Sent Back)')], default='Pending', max_length=20),
        ),
    ]
