# Generated by Django 6.0.4 on 2026-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_courier_name_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Snapshot of SKU', max_length=255, null=True),
        ),
    ]
