# Generated by Django 6.0.4 on 2026-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Manufacturing/Purchase cost', max_digits=10),
        ),
    ]
