# Generated by Django 6.0.4 on 2026-04-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description_en_product_description_gu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_gu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_gu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_hi',
        ),
    ]
