# Generated by Django 6.0.4 on 2026-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_filters_remove_category_layout'),
        ('products', '0004_remove_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='categories.category'),
        ),
    ]
