# Generated by Django 6.0.4 on 2026-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantattributevalue',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
