# Generated by Django 6.0.4 on 2026-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_variantattributevalue_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Leave this field blank to automatically generate a unique SKU based on the product name and selected attributes upon saving.', max_length=255, null=True, unique=True),
        ),
    ]
