# Generated by Django 6.0.4 on 2026-04-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='index',
        ),
    ]
