# Generated by Django 6.0.4 on 2026-04-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantattributevalue',
            options={'ordering': ['index']},
        ),
    ]
