# Generated by Django 6.0.4 on 2026-04-30 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_wishlist_product'),
        ('products', '0013_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='variant',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'variant')},
        ),
    ]
