# Generated by Django 5.2.8 on 2026-04-05 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('slug', models.SlugField(unique=True)),
                ('layout', models.CharField(choices=[('image', 'Image Focused'), ('spec', 'Spec Heavy'), ('compact', 'Compact')], default='spec', max_length=20)),
                ('filters', models.JSONField(blank=True, default=list, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
