# Generated by Django 5.2.8 on 2026-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='category',
            name='layout',
        ),
    ]
